spring.application.name=scheduler
server.port=8082
spring.ai.mcp.server.protocol=stateless
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.jamesward.dev
